version: "3.8"

services:
  budgetbot:
    build: .
    container_name: budgetbot
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    network_mode: host
